apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVpIRFhQVlVVS0FUTUQzVUM=
  AWS_SECRET_ACCESS_KEY: Um5LY2UyYzBaaWRIZGEzRFJNbDIzSE84MzhLUjZUUXRXN3FZMkM5Yw==
  POSTGRES_USERNAME: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
